import { Habit } from "@/types";

export const DEFAULT_HABITS: Habit[] = [
  {
    id: "habit_coffee",
    name: "Morning Coffee",
    emoji: "☕",
    category: "food_drink",
    costPerInstance: 250,
    timePerInstance: 20,
    frequencyPerWeek: 7,
    currency: "₹",
    color: "#f59e0b",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit_uber",
    name: "Uber/Ola Rides",
    emoji: "🚗",
    category: "transport",
    costPerInstance: 180,
    timePerInstance: 30,
    frequencyPerWeek: 5,
    currency: "₹",
    color: "#3b82f6",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit_takeout",
    name: "Food Delivery (Swiggy/Zomato)",
    emoji: "🍕",
    category: "food_drink",
    costPerInstance: 350,
    timePerInstance: 40,
    frequencyPerWeek: 4,
    currency: "₹",
    color: "#ef4444",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit_netflix",
    name: "Netflix / OTT",
    emoji: "📺",
    category: "entertainment",
    costPerInstance: 55,
    timePerInstance: 120,
    frequencyPerWeek: 7,
    currency: "₹",
    color: "#8b5cf6",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit_gym",
    name: "Gym Membership",
    emoji: "🏋️",
    category: "fitness",
    costPerInstance: 60,
    timePerInstance: 75,
    frequencyPerWeek: 3,
    currency: "₹",
    color: "#06b6d4",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit_smoking",
    name: "Cigarettes",
    emoji: "🚬",
    category: "vices",
    costPerInstance: 35,
    timePerInstance: 10,
    frequencyPerWeek: 14,
    currency: "₹",
    color: "#6b7280",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit_alcohol",
    name: "Drinks / Bar",
    emoji: "🍺",
    category: "vices",
    costPerInstance: 600,
    timePerInstance: 180,
    frequencyPerWeek: 2,
    currency: "₹",
    color: "#dc2626",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit_shopping",
    name: "Online Shopping",
    emoji: "🛍️",
    category: "shopping",
    costPerInstance: 800,
    timePerInstance: 45,
    frequencyPerWeek: 2,
    currency: "₹",
    color: "#f43f5e",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit_spotify",
    name: "Spotify / Music",
    emoji: "🎵",
    category: "entertainment",
    costPerInstance: 20,
    timePerInstance: 60,
    frequencyPerWeek: 7,
    currency: "₹",
    color: "#22c55e",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "habit_snacks",
    name: "Snacks & Junk Food",
    emoji: "🍟",
    category: "food_drink",
    costPerInstance: 120,
    timePerInstance: 15,
    frequencyPerWeek: 5,
    currency: "₹",
    color: "#f97316",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
